python move_alfmaps_year_folders.py -p /atlas_scratch/apbennett/IEM/FinalCalib/gfdl_cm2_1.sresa2/Maps/
python move_alfmaps_year_folders.py -p /atlas_scratch/apbennett/IEM/FinalCalib/gfdl_cm2_1.sresa1b/Maps/
python move_alfmaps_year_folders.py -p /atlas_scratch/apbennett/IEM/FinalCalib/gfdl_cm2_1.sresb1/Maps/
python move_alfmaps_year_folders.py -p /atlas_scratch/apbennett/IEM/FinalCalib/miroc3_2_medres.sresa2/Maps/
python move_alfmaps_year_folders.py -p /atlas_scratch/apbennett/IEM/FinalCalib/miroc3_2_medres.sresa1b/Maps/
python move_alfmaps_year_folders.py -p /atlas_scratch/apbennett/IEM/FinalCalib/miroc3_2_medres.sresb1/Maps/
python move_alfmaps_year_folders.py -p /atlas_scratch/apbennett/IEM/FinalCalib/ukmo_hadcm3.sresa2/Maps/
python move_alfmaps_year_folders.py -p /atlas_scratch/apbennett/IEM/FinalCalib/ukmo_hadcm3.sresa1b/Maps/
python move_alfmaps_year_folders.py -p /atlas_scratch/apbennett/IEM/FinalCalib/ukmo_hadcm3.sresb1/Maps/